### ISSUE TITLE
Memory leak with paper plugin and commands

### ISSUE THREAD

**Issue by DasBabyPixel** [TheBlackEntity/PlugManX#17]
Pretty sure there is a typo/memory leak [here](https://github.com/TheBlackEntity/PlugMan/blob/e25a7c6445ceba02837fa11a4829a73648163983/src/main/java/com/rylinaux/plugman/util/PaperPluginUtil.java#L466)
Please confirm if this is intended, I do some hacky stuff with my own command system and need to know if this is the reason or my system

**Comment by TheBlackEntity** [comment]
Pretty sure that's a typo and might be the reason for your issue.

Thanks for pointing it out

**Comment by itsTyrion** [comment]
isn't this fixed with b96f6b3?

**Comment by TheBlackEntity** [comment]
> this is fixed with b96f6b3, right? 

It should, yes, waiting for a response though

**Comment by DasBabyPixel** [comment]
Everything seems to work fine now
