### ISSUE TITLE
Request adaptation 1.20.1

### ISSUE THREAD

**Issue by LiuXueYangNaya** [TheBlackEntity/PlugManX#20]
Is there any plan to adapt the new version 1.20.1？
My server core version is 1.20.1, and I feel a need for this plugin.
It works so well that I can't even find a replacement for it.
I really want you to succeed.

**Comment by TheBlackEntity** [comment]
PlugManX should work just fine on 1.20.1.

Currently running a 1.20.1 server myself and haven't encountered any issues
