### ISSUE TITLE
Paper Plugin Support w/ Promcore/ProSkillAPI

### ISSUE THREAD

**Issue by DevSerae** [TheBlackEntity/PlugManX#21]
Hi there. I'm having problems loading these plugins, and cannot load them at all. When trying to load the plugin with Plugman, I get the error shown below. Are there any updates of the ETA to add paper plugin support?
Thanks.

Screenshot:
![Screenshot 2023-08-23 003829](https://github.com/TheBlackEntity/PlugManX/assets/63316880/2d738d54-cb7b-4a5f-9bcd-69d435eb7a4d)

**Comment by TheBlackEntity** [comment]
Hey!

I currently cannot give any ETA about supporting paper plugins.

I'm really sorry about the inconveniences

**Comment by DevSerae** [comment]
Hopefully this can be implemented soon.
