### ISSUE TITLE
Packet Leak

### ISSUE THREAD

**Issue by SladeHazard** [TheBlackEntity/PlugManX#22]
The plugin sends thousands of packets per second to players after the player has been connected to server for a while... paper's packet limiter starts to kick the player for receiving a lot of packets:

![image](https://github.com/TheBlackEntity/PlugManX/assets/45261094/9f5a648a-33a6-472d-a74b-f04592cedc3f)

I found out that it's plugman by removing all the other plugins 1 by 1, and plugmanx also sends command related packets on first login:
- Image removed -

**Comment by TheBlackEntity** [comment]
Can you please show me your config?

PlugManX shouldn't do anything without

**Comment by TheBlackEntity** [comment]
Can you please show me your config?

I'm going to try to reproduce this.


Is this spam tied to your player count?

**Comment by TheBlackEntity** [comment]
Btw... The IP you tried to hide is still easily readable.

Next time, use a black bar instead

**Comment by SladeHazard** [comment]
not related to plugman ty
