### ISSUE TITLE
The ability to disable plugin downloading...

### ISSUE THREAD

**Issue by MeowIce** [TheBlackEntity/PlugManX#23]
An option to disable `/plugman download` in the config is a good idea to prevent (un-trusted) admins, and hackers from installing backdoor plugins in the server !

**Comment by TheBlackEntity** [comment]
If you don't trust an admin, don't have him as an admin!


I'll add this feature, but if a hacker already has that kind of access to your server, I don't think this will save you

**Comment by MeowIce** [comment]
> If you don't trust an admin, don't have him as an admin!
> 
> I'll add this feature, but if a hacker already has that kind of access to your server, I don't think this will save you

In some situations, if the hacker only has access to the console, the damage may not be much. But if he has access to the console and downloads his malicious plugin with PlugManX, then the damage might increase as he has access to the whole server file with that malicious plugin. I've seen this before.

**Comment by TypicalModMaker** [comment]
Pointless, if your server is vulnerable, hackers have alot of methods to access console
