### ISSUE TITLE
Paper plugin installed PlugManX as dependency, server stalled. (1.20.1)

### ISSUE THREAD

**Issue by Windswipe** [TheBlackEntity/PlugManX#30]
A plugin on my 1.20.1 Paper server installed PlugManX as a dependency. After it was enabled, it sent the Paper compatibility warning, and then the entire server just stalled. I looked in the logs and saw nothing but the manual termination I initiated 25 mins after it stalled. I tried joining the Discord, but it said the link had expired. Can I get some help with this?

**Comment by Windswipe** [comment]
Hmmm. After the relaunch it started just fine, but complained about a "possible broken plugin" that was another dependency of the plugin that installed PlugManX. It appears to have started normally though.

**Comment by TheBlackEntity** [comment]
Hmmm, shouldn't be an issue with PlugManX.

I'm happy to help though :)

Also, here's the updated discord link:
https://discord.com/invite/GxEFhVY6ff

**Comment by TheBlackEntity** [comment]
Can you leave it running for like 5 minutes? It should crash and give us more information

**Comment by TheBlackEntity** [comment]
> Hmmm. After the relaunch it started just fine, but complained about a "possible broken plugin" that was another dependency of the plugin that installed PlugManX. It appears to have started normally though.

That message is sent when PlugManX failed to interact with the jar file.

You might have to re-download this plugin

**Comment by Windswipe** [comment]
A lot. The one that installed PlugManX was Spleef. The other dependency PlugManX complained about being broken was NaruseSecondThreadAPI. I can send the full list of plugins though if it helps.

**Comment by Windswipe** [comment]
> > Hmmm. After the relaunch it started just fine, but complained about a "possible broken plugin" that was another dependency of the plugin that installed PlugManX. It appears to have started normally though.
> 
> That message is sent when PlugManX failed to interact with the jar file.
> 
> You might have to re-download this plugin

I probably will try to redownload it. This is the second time it's given errors though. When I tried to force Spleef to redownload it earlier, it downloaded PlugManX too.

**Comment by Windswipe** [comment]
Ok, nevermind. It appears everything is working now. I was able to log into the server and everything worked as normal. Thanks for your help though.
