### ISSUE TITLE
Errors Unloading Plugins - Problem applies to reloading as well

### ISSUE THREAD

**Issue by Dylan-Buchanan** [TheBlackEntity/PlugManX#32]
https://hastebin.com/share/ufijopatay.ruby

**Comment by TheBlackEntity** [comment]
I am aware of this issue. There was a Pull Request fixing it.

I cannot update on spigotmc and bukkit right now, since I'm in a hospital

**Comment by LoneDev6** [comment]
@TheBlackEntity Get well soon!

**Comment by Dylan-Buchanan** [comment]
Sorry to hear that, I hope you are alright and get well soon. Glad to hear its already fixed, I took a stab at fixing it using the source code and couldn't figure it out :)
